name: Tests

on:
  push:
    branches:
      - master
    path-ignore:
      - 'README.md'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master
    path-ignore:
      - 'README.md'

jobs:
  build:
    if: "github.event.pull_request.draft == false && ! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    strategy:
      matrix:
        nim: ['1.6.12', 'devel']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
        if: runner.os != 'Windows'

      - name: Set up Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}

      - name: Install dependencies
        run: nimble install -d -y

      - name: Run tests
        run: nimble test
      
      - name: Try to build docs
        run: nimble docs
